"""empty message

Revision ID: 14010f6d6918
Revises: a951da23a777
Create Date: 2023-02-09 12:12:03.399580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14010f6d6918'
down_revision = 'a951da23a777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_assigned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_test_question_number_uq', ['test_id', 'question_number'])
        batch_op.create_foreign_key(None, 'tests', ['test_id'], ['id'])

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_scored', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_points_scored', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_scored', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_responses_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_responses_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('points_scored')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('total_points_scored')
        batch_op.drop_column('percentage_scored')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('total_points')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_test_question_number_uq', type_='unique')
        batch_op.drop_column('test_id')
        batch_op.drop_column('question_number')
        batch_op.drop_column('points_assigned')

    # ### end Alembic commands ###
